"""Tests for the HTML display template generated by the renderer."""

from __future__ import annotations

from pathlib import Path

from gitplot.renderer import _default_html, _write_display_html


class TestDisplayHtml:
    """Contract tests for the generated HTML viewer page."""

    def _html(self, tmp_path: Path, filename: str = "gitplot.svg") -> str:
        html_path = tmp_path / "display.html"
        _write_display_html(html_path, filename)
        return html_path.read_text(encoding="utf-8")

    def test_svg_filename_substituted(self, tmp_path: Path) -> None:
        html = self._html(tmp_path, "custom.svg")
        assert "custom.svg" in html
        assert "{{SVG_FILENAME}}" not in html

    def test_uses_fetch_api(self, tmp_path: Path) -> None:
        assert "fetch(" in self._html(tmp_path)

    def test_no_object_element_creation(self, tmp_path: Path) -> None:
        html = self._html(tmp_path)
        assert "createElement('object')" not in html
        assert 'createElement("object")' not in html

    def test_inline_svg_via_innerhtml(self, tmp_path: Path) -> None:
        assert "innerHTML" in self._html(tmp_path)

    def test_content_comparison_before_update(self, tmp_path: Path) -> None:
        # The page must track previously displayed content and compare before updating.
        html = self._html(tmp_path)
        assert "lastContent" in html

    def test_default_html_matches_same_contract(self) -> None:
        html = _default_html("gitplot.svg")
        assert "fetch(" in html
        assert "innerHTML" in html
        assert "lastContent" in html
        assert "createElement('object')" not in html
        assert 'createElement("object")' not in html
