"""Tests for the HTML display template generated by the renderer."""

from __future__ import annotations

from pathlib import Path

from gitplot.renderer import _default_html, _write_display_html


class TestDisplayHtml:
    """Contract tests for the generated HTML viewer page."""

    def _html(self, tmp_path: Path, filename: str = "gitplot.svg") -> str:
        html_path = tmp_path / "display.html"
        _write_display_html(html_path, filename)
        return html_path.read_text(encoding="utf-8")

    def test_svg_filename_substituted(self, tmp_path: Path) -> None:
        html = self._html(tmp_path, "custom.svg")
        assert "custom.svg" in html
        assert "{{SVG_FILENAME}}" not in html

    def test_uses_object_element(self, tmp_path: Path) -> None:
        # <object> loads file:// SVGs without CORS restrictions; fetch() cannot
        html = self._html(tmp_path)
        assert "createElement('object')" in html or 'createElement("object")' in html

    def test_no_fetch_api(self, tmp_path: Path) -> None:
        # fetch() is blocked by CORS when the page is opened from a file:// URL
        # (e.g. via file://wsl.localhost/... on WSL2/Windows)
        assert "fetch(" not in self._html(tmp_path)

    def test_has_onload_for_flash_free_swap(self, tmp_path: Path) -> None:
        # onload ensures the new SVG is fully loaded before the old one is removed,
        # so the user never sees a blank frame between renders
        assert "onload" in self._html(tmp_path)

    def test_preloads_offscreen_before_swap(self, tmp_path: Path) -> None:
        # The new <object> is loaded off-screen while the current one remains visible;
        # only after onload does an atomic replaceChild/appendChild swap occur
        assert "-9999px" in self._html(tmp_path)

    def test_default_html_matches_same_contract(self) -> None:
        html = _default_html("gitplot.svg")
        assert "createElement('object')" in html or 'createElement("object")' in html
        assert "fetch(" not in html
        assert "onload" in html
        assert "-9999px" in html
