"""Tests for the HTML display template generated by the renderer."""

from __future__ import annotations

from pathlib import Path

from visigit.renderer import _default_html, _write_display_html


class TestDisplayHtml:
    """Contract tests for the generated HTML viewer page."""

    def _html(self, tmp_path: Path, filename: str = "visigit.svg") -> str:
        html_path = tmp_path / "display.html"
        _write_display_html(html_path, filename)
        return html_path.read_text(encoding="utf-8")

    def test_svg_filename_substituted(self, tmp_path: Path) -> None:
        html = self._html(tmp_path, "custom.svg")
        assert "custom.svg" in html
        assert "{{SVG_FILENAME}}" not in html

    def test_uses_img_not_object(self, tmp_path: Path) -> None:
        # new Image() / <img> loads file:// SVGs without CORS restrictions.
        # <object> at 1×1px triggers STATUS_BREAKPOINT in Chrome's SVG renderer.
        html = self._html(tmp_path)
        assert "new Image()" in html
        assert "createElement('object')" not in html
        assert 'createElement("object")' not in html

    def test_no_fetch_api(self, tmp_path: Path) -> None:
        # fetch() is blocked by CORS when the page is opened from a file:// URL
        # (e.g. file://wsl.localhost/... on WSL2/Windows)
        assert "fetch(" not in self._html(tmp_path)

    def test_has_onload_for_flash_free_swap(self, tmp_path: Path) -> None:
        # new Image() loads in memory; onload fires when ready, then
        # replaceChild/appendChild moves it into #container atomically so
        # the previous SVG stays visible right up to the swap — no blank frame
        html = self._html(tmp_path)
        assert "onload" in html
        assert "replaceChild" in html or "appendChild" in html

    def test_default_html_matches_same_contract(self) -> None:
        html = _default_html("visigit.svg")
        assert "new Image()" in html
        assert "fetch(" not in html
        assert "onload" in html
        assert "createElement('object')" not in html
        assert 'createElement("object")' not in html
